train:
{
    mode: train
    coordinate: body_coord
    data_list:
    [
        {name: ariaCPF
        window_size: 1000
        step_size: 100
        data_root: ${DATA_ROOT}/aria_processed_cpf_both/train
        data_drive: []
        },
    ]
    gravity: 9.81007
    remove_g: True

}

test:
{
    mode: test
    coordinate: body_coord
    rot_from_gyro: False
    rot_type: None
    data_list:
    [{
        name: ariaCPF
        window_size: 1000
        step_size: 100
        data_root: ${DATA_ROOT}/aria_processed_cpf_both/val
        data_drive: []
    }]
    gravity: 9.81007
    remove_g: True

}

eval:
{
    mode: evaluate
    coordinate: body_coord
    rot_from_gyro: True
    rot_type: None
    data_list:
    [{
        name: ariaCPF
        window_size: 1000
        step_size: 100
        data_root: ${DATA_ROOT}/aria_processed_cpf_both/test
        data_drive: []
    }]
    gravity: 9.81007
    remove_g: True

}

inference:
{
    mode: infevaluate
    coordinate: body_coord
    rot_from_gyro: True
    rot_type: None
    data_list:
    [{
        name: ariaCPF
        window_size: 1000
        step_size: 100
        data_root: ${DATA_ROOT}/aria_processed_cpf_both/test
        data_drive: []
    }]
    gravity: 9.81007
    remove_g: True


}
