train:
{
    mode: train
    coordinate: body_coord
    rot_from_gyro: False
    data_list:
    [   
        {name: tlioCPF
        window_size: 1000
        step_size: 10
        data_root: ${DATA_ROOT}/tlio_dataset_cpf/train
        data_drive: []
        },
    ]
    gravity: 9.81007
    remove_g: True

}

test:
{
    mode: test
    coordinate: body_coord
    rot_type: None
    rot_from_gyro: False
    data_list:
    [{
        name: tlioCPF
        window_size: 1000
        step_size: 10
        data_root: ${DATA_ROOT}/tlio_dataset_cpf/val
        data_drive: []
    }]
    gravity: 9.81007
    remove_g: True

}

eval:
{
    mode: evaluate
    coordinate: body_coord
    rot_type: None
    rot_from_gyro: False
    data_list:
    [{
        name: tlioCPF
        window_size: 1000
        step_size: 10
        data_root: ${DATA_ROOT}/tlio_dataset_cpf/test
        data_drive: []
    }]
    gravity: 9.81007
    remove_g: True

}

inference:
{
    mode: infevaluate
    coordinate: body_coord
    rot_type: None
    rot_from_gyro: True
    data_list:
    [{
        name: tlioCPF
        window_size: 1000
        step_size: 10
        data_root: ${DATA_ROOT}/tlio_dataset_cpf/test
        data_drive: []
    }]
    gravity: 9.81007
    rot_from_gyro: True
    remove_g: True

    
}
